### PR TITLE
bugfix: try xdg-open first to avoid bug in linux

### PR DESCRIPTION
**Pull request by astampoulis**
When running `git pr` or any other command that opens a browser on Linux, I get the error message `Couldn't get a file descriptor referring to the console`. 

The reason is that the browser helpers try the `open` executable first, which exists on Linux, but does not do what it's supposed to (it starts a program on a new virtual terminal). I changed it so that `xdg-open` is tried first instead. This should still work on Mac as the `xdg-open` tool is not available there and `open` will be tried afterwards.

@kevgo @charlierudolph Comments?

### CODE REVIEW

**Comment by charlierudolph** [comment]
Hmm maybe we should just update this to detect the operating system and try the appropriate command? Looks like the command  `uname` can be used to get the operating system name.

**Comment by kevgo** [comment]
I'm for the simpler solution, which is to re-arrange the commands as it is done in this PR. @astampoulis please add a comment why the order matters here, then this is :ship:. Thanks for fixing this!  :+1:

**Comment by charlierudolph** [comment]
Okay. I'm fine with as it then as long as a comment is added explaining the order

**Comment by astampoulis** [comment]
Thanks guys, added the comment! I don't have commit access to the normal git-town repository, so please do the merge if this is OK.

**Comment by kevgo** [comment]
Me have an open commit policy. Once you get your first PR reviewed you get access to the repo. Feel free to squash-merge (using Git Town of course)!  :)

**Comment by astampoulis** [comment]
Closed with <https://github.com/Originate/git-town/commit/ae0622d823b784b8a59d3d2ff00ccd7b35fd79f9>

**Pull request closed without merging**
