### PR TITLE
show ancestry

### PR DESCRIPTION
**Pull request by charlierudolph**
@allewun @kevgo 

A simple implementation of branch ancestry in response to #675

### CODE REVIEW

**Comment by allewun** [comment]
This is pretty clean :) Maybe I'm overvaluing the need for lines...

**Comment by kevgo** [comment]
Wow, I stand corrected. This is much simpler and more elegant than I thought possible.

**Comment by charlierudolph** [comment]
@allewun @kevgo So should this be shipped and #675 closed?

**Comment by kevgo** [comment]
Fine with me. #675 looks nicer, but this doesn't need an external dependency, and that trumps it. :airplane:

**Comment by allewun** [comment]
Agreed

**Pull request closed without merging**
