### PR TITLE
Rename “git-pull-request” to “git-create-pull-request”

### LINKED ISSUE #413: git-pr is used by git-extras
Can't install `git-town` and `git-extras` side by side on homebrew.

```shell
~ > brew install git-town
Linking /usr/local/Cellar/git-town/0.5...
Error: Could not symlink bin/git-pr
Target /usr/local/bin/git-pr
is a symlink belonging to git-extras. You can unlink it:
  brew unlink git-extras
```

What do you think about renaming `git pr` to `git pull-request`. It's more descriptive and I think users should decide what they want their git aliases to be, not git-town.

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun @ricmatsui 

Fixes #413 and #507

### CODE REVIEW

**Comment by allewun** [comment]
:ship: looks like you got them all

**Comment by charlierudolph** [comment]
I disagree with this and want to deal with this collision in a different way.

`git pull-request` and `git-repo` are fundamentally different from the rest of the commands as they integrate with external services and are not just a series of git commands. 

I believe we should move `git pull-request` and `git repo` into their own project where we introduce our own new command, call it `gr` (git remote) for demonstration purposes. We then have  `gr pull-request` and `gr repo` and a user can do the same thing with hub and alias them to git if they want.

**Comment by kevgo** [comment]
I am open to having this conversation, but let's do this separately. This is a bigger architectural refactor, with a lot of pros and cons to it. So, let's do a 2-step approach here: first get this change in to fix the immediate issue that blocks users, harms our reputation as being incompatible with git-extras and hub, and delays a bigger roll-out of GT. Step 1 then gives us the time to talk about how we handle peripheral commands in general, and whether we do a plugin system or separate projects.

Sounds good?

**Comment by kevgo** [comment]
I have added #512 to track the idea of extracting these commands. Let's continue the conversation around extracting there.

**Comment by charlierudolph** [comment]
I think this should be named `new-pull-request` as it opens the form for creating a new pull request instead of actually creating a pull request.

**Comment by charlierudolph** [comment]
The main reason I am against this is that we are basically submitting to another tool. I believe our `pull-request` command is named properly, it just so happens that `hub` has a command with the same name. (something I brought up in #413). Thus we have a competing command with `hub`. I don't think competing is a bad thing, but we focus our energy on where we want to compete. `git pull-request` and `git repo` are nice commands but they have a different market from the rest of the commands.

**Comment by kevgo** [comment]
Good conversation here. 

I like the change to `new-pull-request`. 

In terms of naming, we have a command that creates PRs, and one that ships them, so I think distinguishing the two through more specific naming is appropriate. What does `git pull-request` actually mean? Creating one? Deleting one? Merging one? Commenting on one? Changing one?

In terms of competition, we don't live in a vacuum, and there are other tools around us that we need to be aware of. We have our own focus (providing a generic high-level layer above Git to make it more usable in a generic, vendor-independent and workflow-independent way). There are some overlaps to other tools who provide vendor-specific or workflow-specific Git enhancements. That's okay, and will always be that way. 

If we avoid competition, then we also submit to other tools. Overall I think we should focus on what's best for GT, independent of what others do, while trying to be good citizens in the ecosystem (i.e. don't be incompatible).

**Comment by charlierudolph** [comment]
pull requests are something entirely different from shipping feature branches. Pull requests don't exist in git. They exist on GitHub and Bitbucket and other services. `git ship` would still be useful even if the idea of a pull request changes.

I don't believe the argument that `pull-request` is no generic holds much merit. Its simple and does what you expect. Using that same logic, I think `hack` and `extract` are too generic. I don't know what hacking means in term of git, and extracting what?

**Comment by kevgo** [comment]
I have updated this PR to `new-pull-request`. I think no matter whether we extract this command later or not, this is a good intermediate step.

**Comment by kevgo** [comment]
Leaning on OO principles, where nouns describe objects, and verbs describe actions performed on those objects, I meant that commands (which are actions), should be verbs. Many Git commands are verbs ("checkout"), and the ones that are nouns ("branch") usually need a subcommand to clarify what exactly you want to do with the object described by the noun ("git branch -d" etc). So a noun is only used to cluster a number of related actions, but it is not a stand-alone command. Similar to REST, running a noun command by itself shows all instances of that object type ("git branch" shows all branches). All of our GT commands are therefore also verbs, except "town", which also needs subcommands to qualify actions. 

What does this mean for this command here (creating PRs)? If we provided a comprehensive solution that allows to do several things with PRs, the right way of naming it would be `git pull-request`, with subcommands like (create, approve, comment-on, delete), and with the command showing all PRs if run without a subcommand. Since we only do one thing here, showing a form to create a new PR, the command name should be a verb. "new" isn't really a verb, but close enough here. ;)

**Comment by charlierudolph** [comment]
My main qualm with `create` is that we aren't actually creating a pull request. We are opening a browser to a form for a new pull request (thats why I suggested that). `open-pull-request-form` is probably the most accurate may to use a verb in my mind (though not the most fun to type out)

**Comment by kevgo** [comment]
I agree with your reservations against `create`. If we lean on the Rails nomenclature for REST as a (admittedly very thin) straw here, `new` shows a UI for creating a resource, and `create` actually creates the resource. So I can live with `new` here. Its not perfect, but good enough for me. Also for you?

**Comment by kevgo** [comment]
After talking in person, we agreed to respect [hub](https://github.com/github/hub) and [git-extras](https://github.com/tj/git-extras) as existing state-of-the-art, and keep the name as `git new-pull-request`. So this PR should be ready to merge now. Creating the new command-line application separate from Git is tracked in #515.

**Comment by charlierudolph** [comment]
Need to realphabetize things in a bunch of places (because of the rename of create-pull-request to new-pull-request). After that's resolved this is good to :ship:

**Pull request closed without merging**
