### PR TITLE
Fix broken Windows Colors

### LINKED ISSUE #954: On windows command line, colored output is not working
image

### PR DESCRIPTION
**Pull request by kevgo**
fixes #954

### CODE REVIEW

**Comment by kevgo** [comment]
ping

**Comment by charlierudolph** [comment]
I'm confused when exactly this is needed. It appears that we need to print to `color.Output` only when the string being outputted has colors. It appears you changed a few instances where I don't believe there are uses of colors

**Comment by kevgo** [comment]
We don't want to get into the game of always having to reason/prove whether an outputted string contains color codes or not. I think its more robust to always pipe any output through `color.Output`. This will prevent subtle Windows-specific color bugs when we add or remove colored output in the future.

**Comment by charlierudolph** [comment]
If we want to use this everywhere, thoughts on creating a package `cfmt`, which has the `Printf` / `Println` functions to make this a bit easier to use? Then we should use that always instead of `fmt`

**Comment by kevgo** [comment]
I like your idea of `cfmt`, implemented!

**Pull request merged**
