### PR TITLE
Set correct shebangs

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun 

Fixes the last remaining incorrect shebangs

### CODE REVIEW

**Comment by allewun** [comment]
Is there a reason why the shell overrides are kept as `#!/bin/bash` ?

**Comment by kevgo** [comment]
Ha, no, I just forgot them. Fixed

**Comment by allewun** [comment]
:ship:

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
