### PR TITLE
Update version to 6.0.1

### LINKED ISSUE #1098: git-town version 6.0.0 reports its version as 5.1.0
I just downloaded `git-town-windows-amd64.exe` from the releases page, under release `v6.0.0`. When I run the `version` command, it reports that it is version `5.1.0`. (I renamed the file after downloading it to keep track of which version it is). Otherwise, it does have the new feature that I am aware of (`new-branch-push-flag`):

```
> Get-FileHash .\git-town-windows-amd64-6.0.0.exe | Format-List


Algorithm : SHA256
Hash      : 3B393D671FEFC227C826D7A651A15C14FA949FFBF989CB688239A8666ED3B36C
Path      : C:\Users\kel\Downloads\git-town-windows-amd64-6.0.0.exe


> .\git-town-windows-amd64-6.0.0.exe version
Git Town 5.1.0
> .\git-town-windows-amd64-6.0.0.exe new-branch-push-flag
false
> .\git-town-windows-amd64-6.0.0.exe hack-push-flag
Error: unknown command "hack-push-flag" for "git-town"
Run 'git-town --help' for usage.
unknown command "hack-push-flag" for "git-town"
```

### PR DESCRIPTION
**Pull request by kevgo**
resolves #1098

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can we do a 6.0.1 release that updates the version?

**Comment by kevgo** [comment]
Good idea, updated

**Comment by charlierudolph** [comment]
Can this become the release PR following our guidelines? Thus release notes would need to be updated in this PR

**Comment by kevgo** [comment]
Sorry I haven't done releases in a while. Updated.

**Pull request merged**
