### PR TITLE
Include ignored files in git stash

### LINKED ISSUE #744: git sync: ignored files are deleted
`git sync` seems to like to go on a rampage and delete ignored files. This happened to me twice today. The first time I thought I was going insane. The second time I suspected the tools.

Here's a repro:

```
# Create an empty repo with a .gitignore file
cd $(mktemp -d -t town)
git init
echo "ignored" > .gitignore
git add .gitignore
git commit -m "Initial import"
git town main-branch master

# Hack on a branch, create a file that's ignored
git hack disappear

mkdir -p test/ignored
echo "Very important" > test/ignored/important
cat test/ignored/important 

echo "Also important" > somefile
git add somefile 

# Run git sync
git sync

# Ignored file has disappeared
cat test/ignored/important
```

I also discovered that `git town main-branch master` on an empty repo does not work:

```
-> % cd $(mktemp -d -t town)
bowbaq@bowbaq-home [18:01:10] [/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt] 
-> % git init
Initialized empty Git repository in /private/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt/.git/
bowbaq@bowbaq-home [18:01:15] [/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt] [master]
-> % git town main-branch master
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: no branch named 'master'
```

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @Bowbaq 

fixes #744 

It turns out `git stash -a` does what we want here: stashing all files (including ignored files) away before running `git clean` internally. I'm not sure what `git stash -u` is for, this command sounds dangerous.

### CODE REVIEW

**Comment by kevgo** [comment]
Note: `git stash -a` is pretty slow when there is a large number of untracked files, for example `node_modules` in Node code bases.

**Comment by Bowbaq** [comment]
LGTM.

 If `git stash -a` is slow in certain cases, maybe it's worth adding a configuration option where the user can opt-in to using `git stash -u` with a suitable warning about side effects?

**Comment by charlierudolph** [comment]
I definitely want a configuration option before this goes in. I don't want ignored files in my code base to be stashed

**Comment by kevgo** [comment]
I agree, and want a config option as well. Having to wait 5 sec for each stash/unstash is a PITA and destroys the joy of using Git Town. The question is, what should the default be? Our options are:

- `stash -u`: 
  - __pro:__ in 99% of the cases that's what you want, so it should be the default. We have years of usage of this, on many dozens of projects, without any problems at all. 
  - __con:__ Reasons for not making it the default is that once in a while it eats files, which is a big pain when it happens because its hard to debug. 

- `stash -a`: 
  - __pro:__ more reliable, works in all situations, so it should be the default
  - __con:__ makes the overall Git Town experience slow as molasses, thereby causing the whole product to suck. For something that doesn't even happen in 99% of the cases, and can probably be fixed with better `.gitignore` configuration. So it should not be the default for everybody on every project.

**Comment by kevgo** [comment]
Maybe have no default, but give the user a meaningful explanation upfront what the pros and cons are, and then let the user decide?

**Comment by Bowbaq** [comment]
Maybe it's possible to detect the dangerous patterns in the `.gitignore` file and warn about that instead?

**Comment by kevgo** [comment]
@Bowbaq that would be nice. Two issues here:
- I am not sure I fully understand every permutation that is dangerous
- the user might modify `.gitignore` later. I don't want to have Git Town check this for every command.

**Comment by Bowbaq** [comment]
Good points. On the other hand, a warning when you first setup the tool also doesn't stop you from shooting yourself in the foot later on. As far as I can tell, there is no way to recover the lost files. I was only able to because my working copy happened to be in my Dropbox folder. That's a dangerous edge case to have in this sort of tool.

My vote would be to make `stash -u` the default because it's safe in all cases, with an opt-in to the less safe but faster `stash -a`. That opt-in could be automatically suggested by measuring the runtime of `stash -a` and triggering above a threshold.

**Comment by charlierudolph** [comment]
Could we attack this another way, stage all the untracked files (if there are any) and then using `git stash`? That way we prevent `git clean` from running.

**Comment by kevgo** [comment]
That would be okay with me, since the current Git Town flow destroys the information which file are staged anyways. I assume this is a side effect of stashing changes away. If this reliably prevents `git clean` from running, let's try that!

**Comment by kevgo** [comment]
Implemented @charlierudolph's suggestion in #758, which if merged replaces this PR.

**Pull request closed without merging**
