### PR TITLE
WIP: Use the browser launcher functionality from Github's Hub

### PR DESCRIPTION
**Pull request by kevgo**
implements #874 

- fully working Windows and Linux support, including starting Firefox, Opera, Mozilla, or some other obscure Linux browser
- this does not increase the binary size (still 5MB), since the linker removes code that is not used
- this lays the foundation for using other `hub` code. Hub is also written in Go, so we can use it's code directly here. 
- we are using undocumented internal APIs of `hub` here, which is normally a bad thing. Versioning and vendoring via `glide` ensures that we always use the exact same version of hub, though, so there won't be any surprises unless we manually update dependencies.

@charlierudolph I am posting this PR to get your take on this before I spend time finalizing it.
The build is currently broken because it now correctly tries to use the Linux driver on CircleCI, while before it used `open` even though that does not seem a valid command to open the browser on Linux.
Once you agree with the general direction, I'll think how to make our tests platform independent.

### CODE REVIEW

**Comment by kevgo** [comment]
Current error is that the command to launch the browser is different on Circle now:

```
 | (-) <none>  | (-) open https://github.com/Originate/git-town/compare/feature?expand=1                                                                                                   |
 | (+) <none>  | (+) /home/ubuntu/.go_workspace/src/github.com/Originate/git-town/features/support/shell_overrides/xdg-open https://github.com/Originate/git-town/compare/feature?expand=1 |

**Comment by charlierudolph** [comment]
One quick question related to this. Should we finish the cleanup, merge the go branch into master, and do a alpha release before starting on any other features?

Related to hub, I had envisioned we would be using hub commands not its internals. If the repo was github and hub was installed we might run alternative commands. In some early research for the merge pull request, I ended up deciding to use the github API instead of hub as it didn't look like they had that implemented in a way that you could squash merge.

The browser launcher feels like it should be extracted into its own go library that we and hub can both use.

**Comment by kevgo** [comment]
This isn't a new feature. Just a better implementation of the existing "open in browser" feature in Go. 

I'm not saying we should use hub for everything. It's a pretty shallow and limited tool that doesn't do nearly as much as we need here. What I do say is that I don't want to require the user to having to install hub in order to support repos on Github. I'd rather have GT include any hub functionality we want to use. 

I agree that a dedicated library for opening browsers would be the ideal solution here. This is something that the Github team has to do, though. We can't take their code and release it as our own module. A quick search for third-party libraries only revealed https://github.com/skratchdot/open-golang, which isn't nearly as full-featured as the open functionality from hub.

**Comment by charlierudolph** [comment]
> I agree that a dedicated library for opening browsers would be the ideal solution here. This is something that the Github team has to do, though. We can't take their code and release it as our own module. A quick search for third-party libraries only revealed https://github.com/skratchdot/open-golang, which isn't nearly as full-featured as the open functionality from hub.

I actually ran into this with mocha where they had the great error diffs as part of their codebase. I asked if they would be okay with me extracting that potion of their codebase into its own module. They said yes and I ended up doing that. I'd prefer we do that sort of thing instead of using the undocumented internals of a library

**Comment by kevgo** [comment]
We can try, but I don't have a real interest nor bandwidth for maintaining an ongoing list of different environments to do all the testing for this. I'd rather just apply their approach to our code base and sync in regular intervals.

**Comment by kevgo** [comment]
Bump. Arguments that would speak for keeping this approach are:
- extracting this into a well tested library is cumbersome, we don't have the bandwidth for this and to maintain it moving forward
- with vendoring we are pretty stable even though we use an internal API. As long as we don't update the `hub` dependency, we will never break. And public APIs can also change or go away. The compiler will warn us if the API is different in future versions of hub. So I don't see using an internal API as an issue here. 
- we might want to loop in the Hub codebase into GT anyways in the future, for example to read user credentials stored by hub on the user's hard drive, or to talk to the Github API.

**Pull request closed without merging**
