### PR TITLE
Specs for command pattern

### PR DESCRIPTION
**Pull request by allewun**
Was starting to work on #414 but along the way determined that the command pattern needed some specs first.

Using a new `git-mock` script as a template that's generated during the tests, with customizable `preconditions` and `steps` in the specs. Decided to make a PR before going too far with this.

The only functional change is removing the steps file after running the steps. Not sure why we're keeping them around?

@kevgo @charlierudolph

### CODE REVIEW

**Comment by kevgo** [comment]
I have a number of concerns around this change:

* These feature specs don't define end-user value, but technical implementation details. I would argue that we don't care about when preconditions are run, as long as the respective Git Town command ends up executing the right Git commands, and making the right changes.

* this change adds a mock Git command (with associated infrastructure) to the real Git Town production system, which shouldn't be there, and is confusing

* these specs verify things that we don't necessarily care about, like whether some temp data is cleaned up. We need to keep some temp data around anyways (undo steps, abort steps etc).

* these specs are brittle, since they define technical implementation details. If we ever refactor our internal Git command structure, they will produce false negative breakages.

Hence I'd rather not do this. We could add the verification that the steps file is cleaned up to the "real" feature specs if we wanted to, for example in https://github.com/Originate/git-town/blob/master/features/support/env.rb#L62. If some specs keep the steps file, we could add a Cucumber tag similar to https://github.com/Originate/git-town/blob/master/features/support/env.rb#L69

**Comment by allewun** [comment]
I agree... glad I asked before going further.

Regarding your 3rd point though, I think temp files are things that users *might* care about. The spec I added (and hence my original question) was for ensuring that step files are removed when they are done executing. I can't see why we would keep them around. The undo steps / abort are a different story though, I'm not touching those at all.

Anyway, the main reason for starting down this path was so I could test #414.

**Comment by kevgo** [comment]
Okay, you convinced me about the temp files. Let's add the verification for them, but to the normal specs. I provided a hint for how to do this possibly.

I think you can verify #414 solely through black-box testing (which we do right now):
* start the `git sync`
* after x sec, send it the kill signal
* verify that there is some output (this has to be vague, since the output can vary)
* verify that there is a steps file left 
* run `git sync --retry` and verify that after running it the Git workspace is in the expected state
* run `git sync --abort` and verify that after running it the Git workspace is in the expected state

**Comment by allewun** [comment]
Should those steps you've outlined be repeated for every `git-*` command? That seems a bit redundant as they all share the same underlying pattern, but the only other alternative I see is what I did the first time.

**Comment by kevgo** [comment]
I'd say doing them for one command is better than doing them for 0 commands, so let's start with that and see how we feel about it then.

**Comment by kevgo** [comment]
Actually we can now put this feature spec into https://github.com/Originate/git-town/blob/master/features/shared, similar to https://github.com/Originate/git-town/blob/master/features/shared/continuing_after_success.feature.

**Comment by allewun** [comment]
Yep that's a good place for it

**Comment by charlierudolph** [comment]
@allewun looks like this has done in a different direction. Can this PR be closed and a new PR/issue be opened with the new idea?

**Comment by allewun** [comment]
Yeah this is stale. Gonna close.

**Pull request closed without merging**
