### PR TITLE
More compressed command-line option documentation

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun 

Aggregates the description for command-line options that semantically belong together.

Implements #385

### CODE REVIEW

**Comment by allewun** [comment]
:+1:

**Comment by charlierudolph** [comment]
Need parens around each.

**Comment by kevgo** [comment]
Parentheses added

**Comment by kevgo** [comment]
all comments addressed

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
