### PR TITLE
Restore original repo name

### PR DESCRIPTION
**Pull request by kevgo**
This PR removes the need to rename the Git repo to `gt`.

implements #797 

@charlierudolph @Bowbaq

### CODE REVIEW

**Comment by charlierudolph** [comment]
Thoughts on also moving `cmd/root.go` (and hack / version) to `cmd/gt/root.go`? Since we are planning on moving the other folders out of `cmd`, anyway I think it'd be nice if all the commands were now just under `cmd/gt`

**Comment by charlierudolph** [comment]
Also won't all the imports need to change? For example `"github.com/Originate/gt/cmd/util"` should need to become `"github.com/Originate/git-town/cmd/util"`?

**Comment by kevgo** [comment]
I see this more as this code base providing a bunch of commands (hack, sync, etc), and `cmd/gt` just defining an alias for that command. It's not that `cmd/gt` exports git town, and `cmd/foo` some other binary with completely different commands.

Where do you see `github.com/Originate/gt/cmd/util` still being used on this branch?

**Comment by charlierudolph** [comment]
Does this have the `gt hack` commits merged into it?

**Comment by kevgo** [comment]
Now it does

**Comment by charlierudolph** [comment]
And now the tests fail. I believe any imports of our lib folder will need to be updated per my earlier comment

**Comment by kevgo** [comment]
Hey, how did you know I pushed changes that fix the build?  :)

**Comment by charlierudolph** [comment]
If you are watching a PR you get notifications every time changes are pushed

**Pull request closed without merging**
