### PR TITLE
remove name clash

### PR DESCRIPTION
**Pull request by charlierudolph**
@kevgo @allewun 

Add a `town-` prefix to all commands in order to prevent naming conflicts. We can easily alias to keep it as is for normal usage but it can be accessed separately.

### CODE REVIEW

**Comment by kevgo** [comment]
I agree with the overall direction. Before we merge this in, let's agree on the details here. I'm not sure running `git town-sync` is the best user experience. I see these possibilities:

- expand the `git town` command to run our commands. E.g. users run `git town sync`.

- create a `gt` or `town` command that calls `town-<command>`. E.g. calling `gt sync` or `town sync` runs `git town sync`. This could be easily written in Bash. We would be completely out of the Git namespace here, and its even shorter than running `git sync`.

- optionally create `git-<command>` aliases via a wizard. Users start the wizard via `git town aliases`. It goes through all Git Town commands, checks if there is an existing `git <command>` command in the system. If yes it warns the user. If not, it asks the user whether to install the alias.

@charlierudolph @allewun thoughts?

**Comment by charlierudolph** [comment]
I considered the first two possibilities and found the current approach the fastest and simplest. Minimal change, prevents naming conflicts via a namespace and takes advantage existing git support.

> expand the `git town` command to run our commands. E.g. users run `git town sync`

The only time I expect someone to type of town-sync is when they have sync aliased to something else. I expect everyone else to use the aliases. Also if we do that then we lose git from autofinding all the subcommands git town adds (like how it suggests sync is a subcommand right now)

This also puts the other config options `main-branch` etc on the same level. I think we should move those under `git town config` or something if we go with this approach. I don't see much benefit to this over the current approach though. Yeah we got rid of a single `-` but at the cost of moving a lot of stuff around and implementing our own redirection.

> create a gt or town command that calls town-<command>. E.g. calling gt sync or town sync runs git town sync. This could be easily written in Bash. We would be completely out of the Git namespace here, and its even shorter than running git sync.

I like the natural feeling of git so I didn't think it was worth moving out of the git. We could setup aliases to keep the current approach easy enough but I'm not a bit fan of this. Git already has the aliasing built in so I figured taking advantage of that was the easiest thing we could do.

> optionally create git-<command> aliases via a wizard. Users start the wizard via git town aliases. It goes through all Git Town commands, checks if there is an existing git <command> command in the system. If yes it warns the user. If not, it asks the user whether to install the alias.

Why do we need a wizard? Simple git aliases are really easy. The major case of people just using git-town have it easy and the rest can easily control their own aliases. We can update the current alias script to not overwrite existing aliases.

**Comment by charlierudolph** [comment]
@kevgo any more thoughts?

**Comment by kevgo** [comment]
Sorry for the delay, I got pulled into many other things. I'm fine with this direction, as long as we make it easy for the user to set up these aliases. Most people don't know what a Git alias is and how to set one up. Ideally some sort of script sets up the aliases. In case of a conflict it proposes a better name for the alias and asks the user what to do.

**Comment by kevgo** [comment]
🚢

**Comment by charlierudolph** [comment]
I added a script for aliasing but its minimal at the moment and just skips commands where a conflicting alias already exists. We can improve it as desired. Just a heads up that merging this means the next release will be 2.0 since this is a breaking change (although very easy to go back to the previous with the alias script)

**Pull request closed without merging**
