### PR TITLE
remove man files

### PR DESCRIPTION
**Pull request by charlierudolph**
They are outdated. We would only have 1 since we are now a single command. All this info is also in the documentation/commands folder (which I will be updating in a separate PR)

### CODE REVIEW

**Comment by kevgo** [comment]
I would like to have this type of information in the CLI. For example, when running `git town help ship`, it currently prints:

```
Deliver a completed feature branch

Usage:
  git-town ship [flags]

Flags:
      --abort            Abort a previous command that resulted in a conflict
      --continue         Continue a previous command that resulted in a conflict
  -m, --message string   Specify the commit message for the squash commit
      --undo             Undo a previous command
```

This isn't as useful as the old man pages were. I still would like to see their content here. Telling the user to go online and find documentation on Github isn't a good user experience.

**Comment by charlierudolph** [comment]
We can put more information there with #851.

**Comment by kevgo** [comment]
The man pages contain a lot of CLI specific formatting. What do you think about us doing #851 first and then shipping this PR?

**Comment by charlierudolph** [comment]
I doubt we are going to need any of the formatting but I'm fine doing it in that order

**Comment by kevgo** [comment]
#921 removes the block, so this can 🚢 now!

**Pull request merged**
