### PR TITLE
cleanup command descriptions

### PR DESCRIPTION
**Pull request by charlierudolph**
* remove duplication as short is used if long is not specified
* make all descriptions have the same tense

### CODE REVIEW

**Comment by charlierudolph** [comment]
Can we add those in another PR? This is just drying up current the implementation

**Comment by charlierudolph** [comment]
@kevgo bump

**Comment by kevgo** [comment]
Woops, I must have missed your reply. Yes, we can add the man pages into the long form in another PR. I suggest keeping the long versions until that happens (which will be soon, I can help with this). Otherwise, we have to add them back later.

**Comment by charlierudolph** [comment]
I'd like to merge this as is though as removing the duplicated long forms doesn't change any functionality (long is defaulted to the short value if not present)

**Pull request merged**
