### PR TITLE
Update to ShellCheck 0.3.6

### PR DESCRIPTION
**Pull request by kevgo**
@allewun @charlierudolph @ricmatsui 

ShellCheck 0.3.6 was released, and it brings new checks. This PR creates the necessary updates to pass the linter.

### CODE REVIEW

**Comment by ricmatsui** [comment]
Looks good to me!

**Comment by charlierudolph** [comment]
Interesting having all variables in SCREAMING_CASE. Makes them stand out but still weird. :ship:

**Comment by kevgo** [comment]
These are global constants. And the convention for constant is SCREAMING_CASE. That's why ShellCheck accepts them to be used in files without being defined there.

**Comment by charlierudolph** [comment]
Auhh okay didn't notice this was only global variables. Cool

**Pull request closed without merging**
