### PR TITLE
Create consistent branch order on configuration

### PR DESCRIPTION
**Pull request by allonsy**
When I configure for the first time on a repo, there is non-determinism in how I select perennial branches. 
For example, consider I have a repo with a `master` branch and a perennial `dev` branch.
When I configure for the first time, the flow goes like this:

```
Git Town needs to be configured

  1: dev
  2: master

Please specify the main development branch by name or number (current value: None): 2
Please specify a perennial branch by name or number. Leave it blank to finish (current value: ): 1
Please specify a perennial branch by name or number. Leave it blank to finish (current value: ): 

[dev] git fetch --prune

Feature branches can be branched directly off 
master or from other feature branches.

The former allows to develop and ship features completely independent of each other.
The latter allows to build on top of currently unshipped features.

  1: master
  2: dev

Please specify the parent branch of dev by name or number (default: master): 1


[dev] git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

[master] git rebase origin/master
Current branch master is up to date.

[master] git checkout dev
Switched to branch 'dev'
Your branch is up-to-date with 'origin/dev'.

[dev] git merge --no-edit origin/dev
Already up-to-date.

[dev] git merge --no-edit master
Already up-to-date.
```
Then, checking the `.git/config` file we see that master was set to the main and perennial branch.
This is because in the configure flow, the `get_numbered_branch` selects numbers according to main branch first. The first time we print out the branches, there is no main branch so the branches are echoed  in alphabetical order. However, when we select a perennial branch, a main branch has been selected so the order that `get_numbered_branch` sees is different than what was echoed to the screen. I resolve this by creating a consistent alphabetical order in the configure step. 
This may also fix the issues encountered #726 although I'm not certain without more testing on my end.

### CODE REVIEW

**Comment by kevgo** [comment]
Thanks for this fix @allonsy! Hmm, this seems like a pretty serious bug, I wonder why we weren't running into it before. Anyways, looks good to me. 

What's your take @charlierudolph and @allewun?

**Comment by kevgo** [comment]
Please update the tests in https://github.com/Originate/git-town/blob/master/features/git-town/configuration/setup.feature

**Comment by allonsy** [comment]
@kevgo added tests

**Comment by kevgo** [comment]
Beautiful! 🚢  Thanks @allonsy!

**Comment by allonsy** [comment]
merged in with 147126fc629e04a73f647ab885a1795125a4d3ed

**Pull request closed without merging**
