### PR TITLE
Remove feature specs without open changes

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun @ricmatsui 

This removes some old specs while implementing some necessary changes.

implements parts of #529

### CODE REVIEW

**Comment by charlierudolph** [comment]
Couldn't this be into master instead of into one of your other branches?

**Comment by charlierudolph** [comment]
It also has quite a few unrelated changes where you are just updating the order steps are performed in

**Comment by kevgo** [comment]
The branch is cleaner and focussed now, given that I have pulled some of its changes into ancestor branches to make them pass. I can't ship it before I ship `kg-nested-branches-2-ship`, since it depends on the contents of these files being in a certain state.

**Comment by kevgo** [comment]
All comments addressed

**Comment by charlierudolph** [comment]
I disagree with moving files from
`features/git-ship/current_branch/on_feature_branch/without_open_changes/*.feature`
to
`features/git-ship/current_branch/on_feature_branch/*.feature`

`git-ship` guards against shipping with open changes and I think that helps differentiate it. 
If you want to debate that further I'd suggest having a separate PR for that as its not related to removing feature specs without open changes

**Comment by charlierudolph** [comment]
I still think these changes can be ported to just be against master instead of into one of your branches.

**Comment by kevgo** [comment]
I have reverted the rename for `current_branch`. This PR exclusively removes redundant specs without open changes in `features/git-ship/supplied_branch` now. Plus one file name fix.

**Comment by kevgo** [comment]
The remaining changes move files around that contain changes from previous feature branches. I'm concerned that this will lead to substantial merge conflicts in all 6 other PRs, so I'd rather keep this PR where it is.

**Pull request closed without merging**
