### PR TITLE
Reduce egocentric steps

### PR DESCRIPTION
**Pull request by kevgo**
Too many steps start with "I ...". This PR changes "I run" to "running", which reads better and reduces repetitiveness.

implements #871

### CODE REVIEW

**Comment by charlierudolph** [comment]
How does it reduce repetitiveness? Are you referring to how `I` is repeated?  Is this part of a larger plan to reduce the use of `I` in other steps as well? 

This is more characters and I feel may be harder to read. 

Aside: I don't really like the use of the term egocentric here. Its definition (on google): "thinking only of oneself, without regard for the feelings or desires of other" doesn't really seem to apply here. This is a hypothetical user, that we refer to in the first person. I'm not surprised the test suite would develop an ego though with how comprehensive it is 😄

**Comment by kevgo** [comment]
Yes, this is so that not every step starts with "I". We can call it "ego-focussed" if you don't like the (admittedly a bit humorously abused) term "egocentric".

This reads much nicer:
```cucumber
Given I have an old configuration file with main branch: "main"
When running `git town-hack new-feature`
Then my repo is configured with the main branch as "main"
...
```

compared to the old:

```cucumber
Given I have an old configuration file with main branch: "main"
When I run `git town-hack new-feature`
Then my repo is configured with the main branch as "main"
...
```

And yes, this is as part of a larger cleanup of Gherkin based on our finding from the last couple of years. I have a bunch of Go changes planned, but can only apply them once all the commands are converted, so I'm doing such peripheral improvements right now.

**Comment by charlierudolph** [comment]
Between "When running ..." and "When I run ...", I prefer the latter.

---

> And yes, this is as part of a larger cleanup of Gherkin based on our finding from the last couple of years.

Can you share what the planned larger cleanup is? Personally, if we using the "Given / When / Then" keywords I care the most about readability and don't believe having a lot of "I"s is a bad thing. An alternative approach could be to just use "*" as the keyword and thus the steps don't start with an english word. 

```
* have an old configuration file with main branch: "main"
* run `git town-hack new-feature`
* repo should be configured with the main branch as "main"
```

**Comment by kevgo** [comment]
I do not have the entire big picture in my head. Like refactoring, I am just following certain basic principles until I'm happy with the code setup, like:
* try to use the actual actor as the subject in a step, i.e. say `Then file "foo" contains the undo steps` instead of `Then I have file "foo" on my disk that contains the undo steps`
* too much repetition should be avoided because it makes the spec read monotonous or like a computer program
* steps should be on the same level at which a normal human would think about this when trying to understand how this works

This PR rounds out some edges that violate rule #2.

**Comment by kevgo** [comment]
@charlierudolph bump. I still believe that the changes in this PR makes the most sense between all discussed alternatives. It doesn't matter whether a command is executed by the user or by some other mechanism like a tool that runs GT commands. Therefore, saying "when running xxx" makes more sense and reads better than saying "When I run xxx".

**Comment by charlierudolph** [comment]
I still don't `When running xxx` since it doesn't sound to me like `xxx` finishes. I think `When running` sounds wrong to me because I'm used to hearing `While running`.  Thoughts on `When xxx is run`?

**Pull request closed without merging**
