### PR TITLE
Prune command

### LINKED ISSUE #777: git town cleanup
Removes any items in the git config related to git town that are no longer needed. 
Just a tool for rare cases when the metadata gets left due to using non git-town commands.

related #741

### LINKED ISSUE #1102: git town prune
> When having used Git Town for a while
I want to be able to clean up the documentation
So that my Git configuration isn’t littered with outdated entries. 

- running “git town config prune” deletes all Git Town configuration
  for branches that don’t exist in the local workspace

### PR DESCRIPTION
**Pull request by kevgo**
resolves #1102 
resolves #777

### CODE REVIEW

**Comment by kevgo** [comment]
> I think I prefer keeping prune-branches and moving git town prune config to git town config prune.

What separates Git Town from Git is that with Git Town there should always be a single command that does something. This means there should be a single command to tidy up the local client. This includes everything that Git Town knows to do here: remove stale branches, outdated config info, and anything else we come up with in the future.

I don't care how we call this command, but I do care that such a command exists in the form of a single command. Since `git prune` is already taken, what do you think about `git cleanup`? I'm also fine keeping `git town prune` and not aliasing it, since it will be used very rarely. 

What do you think?

**Comment by charlierudolph** [comment]
I think prune-branches is a good standalone command for anyone with multiple machines, so I'd prefer to not have that merged into another command.

I don't agree with merging these to clean up everything as I don't think branches with an invalid is on the same level as something like outdated git config.

Thinking more on outdated git config, I think I'd prefer to actually auto-clean up outdated config when you run any git-town command. When we initialize the config map, we can delete anything that is outdated.

**Comment by kevgo** [comment]
Okay, I can get behind auto-pruning the configuration information when running Git Town commands. Automation is good! Hopefully it doesn't make commands much slower.

**Comment by charlierudolph** [comment]
Closing as we went with #1127

**Pull request closed without merging**
