### PR TITLE
Install shellcheck from trusty-backports over cabal

### PR DESCRIPTION
**Pull request by doismellburning**
No need to maintain an install script, less $PATH hackery, less CircleCI
cache faff

### CODE REVIEW

**Comment by doismellburning** [comment]
[I saw a post about how y'all are installing shellcheck on CircleCI](https://discuss.circleci.com/t/shellcheck/2346/3?u=doismellburning), [came up with a way that, broadly speaking, felt simpler](https://discuss.circleci.com/t/shellcheck/2346/4?u=doismellburning) and thought y'all might find it useful (though it's not _objectively_ better, e.g. if you care about specific version!)

**Comment by kevgo** [comment]
Thanks a ton for this contribution @doismellburning! Great to see that ShellCheck is finally available via the proper channels. Happy to get rid of our complicated and crufty way to set it up manually before.

What do you think @charlierudolph?

**Comment by charlierudolph** [comment]
Looks good to me

**Comment by doismellburning** [comment]
Awesome, cheers both!

**Comment by charlierudolph** [comment]
I'm going to revert this in a new PR because this locks us to version 0.3.3. We had previously been on 0.4.1 and I want to update us to 0.4.5

**Comment by doismellburning** [comment]
Bleh, completely understand. I guess I've always wanted to learn how to get stuff into Backports!

**Pull request merged**
