### PR TITLE
Cache Ruby dependencies

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun @ricmatsui 

This caches the installed Ruby gems, thereby saving some time on Circle. It still installs Ruby. Caching the installed Ruby is also possible, but takes 3.5 minutes to restore, so I'm not doing it.

### CODE REVIEW

**Comment by allewun** [comment]
Cool, :shaved_ice:

**Comment by allewun** [comment]
oops :ship: , but shaved ice is cool. Will this be noticeable on xrayci?

**Comment by charlierudolph** [comment]
I really expected CircleCI to automatically do this and it appears they are. Look at the latest master builds and the "Restore cache" / "Save cache" sections of the build.

Below is the "Save cache" portion

---------------------------
Creating dependency cache from any directories in:
**'/home/ubuntu/git-town/vendor/bundle'** '/home/ubuntu/virtualenvs' '/home/ubuntu/.m2' '/home/ubuntu/.ivy2' '/home/ubuntu/.bundle' '/home/ubuntu/.go_workspace' '/home/ubuntu/.gradle' '/home/ubuntu/.cache/bower' '/home/ubuntu/git-town/node_modules' '/home/ubuntu/.cabal'
Creating source cache from:
'/home/ubuntu/git-town/.git'

**Comment by kevgo** [comment]
Great catch. It apparently also caches `~/.cabal/`, so we can now get rid of all manual caching overrides. I pivoted this PR to that.

**Comment by charlierudolph** [comment]
I'm uncertain if that ~/.cabal/ is there because we added it or if its there by default/

**Comment by kevgo** [comment]
You are right. Closing this PR.

**Pull request closed without merging**
