### PR TITLE
Avoid stash -u

### LINKED ISSUE #744: git sync: ignored files are deleted
`git sync` seems to like to go on a rampage and delete ignored files. This happened to me twice today. The first time I thought I was going insane. The second time I suspected the tools.

Here's a repro:

```
# Create an empty repo with a .gitignore file
cd $(mktemp -d -t town)
git init
echo "ignored" > .gitignore
git add .gitignore
git commit -m "Initial import"
git town main-branch master

# Hack on a branch, create a file that's ignored
git hack disappear

mkdir -p test/ignored
echo "Very important" > test/ignored/important
cat test/ignored/important 

echo "Also important" > somefile
git add somefile 

# Run git sync
git sync

# Ignored file has disappeared
cat test/ignored/important
```

I also discovered that `git town main-branch master` on an empty repo does not work:

```
-> % cd $(mktemp -d -t town)
bowbaq@bowbaq-home [18:01:10] [/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt] 
-> % git init
Initialized empty Git repository in /private/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt/.git/
bowbaq@bowbaq-home [18:01:15] [/var/folders/xb/_0dn98hj5zvbx7ly_r4s1r400000gn/T/town.RCs7cpBt] [master]
-> % git town main-branch master
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: no branch named 'master'
```

### PR DESCRIPTION
**Pull request by kevgo**
fixes #744 
alternative to #745 

This PR implements @charlierudolph's [idea](https://github.com/Originate/git-town/pull/745#issuecomment-248042786) to first stage all uncommitted files, so than we can then run a normal `git stash` instead of the dangerous `git stash -u`, thereby avoiding that Git runs `git clean` that will sometimes remove ignored files that are still needed.

@charlierudolph @Bowbaq

### CODE REVIEW

**Comment by Bowbaq** [comment]
LGTM. Is there a way to add a feature test for the use case in #744 to make sure there aren't regressions down the line?

**Comment by charlierudolph** [comment]
I like it. I agree with @Bowbaq that we should look for a way to feature test #744. Hopefully the example he gave there could be used.

**Comment by kevgo** [comment]
I added the test, verified that it breaks with the current `master`, and this branch fixes it. Ready for another review!

**Comment by Bowbaq** [comment]
👍

**Pull request closed without merging**
