### PR TITLE
Lowercase error messages

### PR DESCRIPTION
**Pull request by kevgo**
implements #801

### CODE REVIEW

**Comment by charlierudolph** [comment]
I don't think the `go` branch should update the bash code. This could be done in two parts where we update master to change the bash code to use lowercase messages and then the go branch can conform to that. Otherwise I'd suggest we just update the error messages currently implemented by go in this PR and can update the rest as we get to them.

**Comment by kevgo** [comment]
I agree its not clean, but I want to update all the tests now, and the two alternatives proposed by you have major issues:
* If I don't update at least the Bash commands which are currently not implemented in Go, their tests will break.
* if I update all the Bash commands and tests in a separate feature branch cut from master, I will break the `go` branch until the PR that updates the existing Go code is merged.

Overall this is a big headache and not worth the effort, since the goal is to throw away the Bash code in the near future. So let's not worry too much about correct updating of the Bash code, and focus on getting the Go code correct and the tests green.

**Comment by charlierudolph** [comment]
Ok. On a related note, I actually have been working with `go` as a perennial branch. This way we  can merge `master` into `go` via a child branch of go and can thus make a PR when something breaks or just merge if green.

**Comment by charlierudolph** [comment]
I don't like the look of this. In most cases we report errors that look like this
```
  Error
  This is the error message
```
Making that something like
```
  error
  this is the error message
```
Doesn't look very nice to me. I'm all for removing the periods from incomplete sentences but I'd rather we keep the capitalization.

**Comment by kevgo** [comment]
Okay, closing this. Let's possibly re-visit once we got everything up and running.

**Pull request closed without merging**
