### PR TITLE
Essential subshell commands

### PR DESCRIPTION
**Pull request by kevgo**
Git Town runs most Git commands without checking their exit code. Returning errors from all these places would make the code very cumbersome so I don't want to do it. At the same time, there is nothing we can do if Git doesn't work properly except exit. So I'm imitating the API of [regexp.MustCompile]( https://golang.org/pkg/regexp/#MustCompile) by introducing `command.MustRun`. What do you think?

### CODE REVIEW

**Comment by charlierudolph** [comment]
There are a few commands in `src/git/config` that I think would need to be updated. Thoughts on moving err out of the result object and having the functions return `res, err`? Then `MustRun` would only return `res` and a linter should be able to tell us if we are ignoring errors

**Comment by kevgo** [comment]
There is one command (getting the previously checked out branch) that I couldn't update because it errors if there is no previously checked out branch. Same for the commands to detect if a folder is a Git repo.

Separating the err out is the next step I had planned for this refactor! It will definitely make this more idiomatic. What's holding me up is the fact that there are two types of error here:
1. it couldn't run the command at all because the command doesn't exist
2. it ran the command and the command returned an error

Maybe this is a good chance to use different error types together with the [better error handling introduced by Go 1.13](https://blog.golang.org/go1.13-errors).

**Comment by kevgo** [comment]
Just to be clear, I prefer to do the refactorings we talk about here in a separate PR once this one here is shipped.

**Comment by charlierudolph** [comment]
Okay. I'm good with the other refactor being in another PR but still think there are places in `src/git/config.go` that need to be updated (`GetRemoteOriginURL`, `setGlobalConfigValue`, `setLocalConfigValue` + maybe remove config value but unsure about those)

**Comment by kevgo** [comment]
Good idea to also convert `command.RunInDir`, I didn't think about that! I have converted all occurrences of it in the entire codebase that can be converted. The remaining ones fail for some tests. I don't see any occurrences of `command.RunDirEnv` that could be converted either, so that should be it. Can you please take another look at this PR?

**Pull request merged**
