### PR TITLE
Add missing error checks

### PR DESCRIPTION
**Pull request by kevgo**
Found by the linter.

@charlierudolph

### CODE REVIEW

**Comment by charlierudolph** [comment]
I had tried to encapsulate this in the fetch step. Since we are pulling this logic out, that step can be simplified.

**Comment by kevgo** [comment]
It's fine encapsulating this in the fetch step, but then the `Run` method of it shouldn't return an error object. The linter is correct in pointing out that we are ignoring a potential error here.

**Comment by charlierudolph** [comment]
I don't believe FetchStep is used as a generic step anywhere as its always run in the preconditions instead of during the run phase so we could probably update it to not return anything. Maybe we can just create a function called `steps.Fetch()` that doesn't return an error and remove `FetchStep`?

**Comment by kevgo** [comment]
Sorry I misread your initial comment (that's what jet lag does to you). I have removed the error handling from FetchStep.

**Comment by charlierudolph** [comment]
This introduced a lot of duplication. I'd prefer we just have the steps package (or some new package) export a Fetch function that has the following implementation:
```go
func Fetch() {
  err := script.RunCommand("git", "fetch", "--prune")
  if err != nil {
    log.Fatal(err)
  }
}
```
FetchStep could then be removed. Its not used as a step anywhere at the moment as its always run in preconditions. Its similar to a step in how it uses script.RunCommand (which otherwise only appears in the Run functions of steps) but thats it.

**Comment by kevgo** [comment]
I agree this is much cleaner now. I had to put the new helper function into the `scripts` package to avoid a circular dependency.

**Comment by kevgo** [comment]
All comments addressed

**Pull request closed without merging**
