### PR TITLE
User stories for git-town

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun adding user stories that describe end-user value

### CODE REVIEW

**Comment by kevgo** [comment]
all comments addressed

**Comment by charlierudolph** [comment]
Looks good. Only thing I'd like to bring up is changing "main development branch" to "main branch". The git-town subcommand in "main-branch" and we refer to it almost everywhere else as the "main branch".

**Comment by kevgo** [comment]
Yeah, I like shorter names better. Renamed.

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
