### PR TITLE
Document debugging Godog

### PR DESCRIPTION
**Pull request by kevgo**
I have finally figured out how to debug Godog specs. 
This knowledge is non-trivial, we should document it.

### CODE REVIEW

**Comment by charlierudolph** [comment]
What exactly does debug mean in this case? Is this just running a single test or something else?

**Comment by kevgo** [comment]
Running godog in the VSCode debugger, setting breakpoints, executing code line by line while looking at variables in the inspector. This form of “manual testing” is generally not used very often since we have automated tests to triage bugs, but sometimes the most efficient approache, especially when dealing with complex data structures in test code itself (which doesn’t have tests).

**Comment by charlierudolph** [comment]
Okay good to know. Can we add another bullet to the docs then that mentions breakpoints set in vscode?

**Comment by kevgo** [comment]
Good idea. I have also made more clear that this is for debugging test code, since our production code is covered by the automated tests.

**Pull request merged**
