### PR TITLE
kill spec improvements

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun 

I think these branch names are more descriptive. What do you think?

### CODE REVIEW

**Comment by kevgo** [comment]
all comments addressed

**Comment by charlierudolph** [comment]
I personally dislike `good-feature`. It's too generic and doesn't tell me more than `feature`. That is meant to represent a feature that is in active development right? What about naming if `active-feature` or something along those lines?

**Comment by kevgo** [comment]
Renamed good-feature to active-feature. Please take another look!

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
