### PR TITLE
Remove Rake

### PR DESCRIPTION
**Pull request by kevgo**
We don't need Rake at all, since we only have very simple scripts to run things.
We have the bash scripts in `bin/` anyways, so why not use them directly.

### CODE REVIEW

**Comment by kevgo** [comment]
Do all the fixers also run all the lint tests? I am okay with the distinction into scripts that only report errors, and those who focus on fixing a subset of them.

**Comment by kevgo** [comment]
I am going to merge this in as-is since it is approved. We can keep fine-tuning the way we name fix scripts across our code bases on an ongoing basis down the line.

**Comment by charlierudolph** [comment]
My rename was suggested is because we are only fixing lint errors and i think the use of "fix" is too generic

**Comment by kevgo** [comment]
I see this more of running all sorts of auto fixes. Those include lint errors and other generic gofixes like our exitfix tool. Maybe we call it “autofix” to make it clear that this only applies programmatic improvements?

**Pull request merged**
