### PR TITLE
Feature spec for killing the current branch

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun @ricmatsui 

implements #567

### CODE REVIEW

**Comment by charlierudolph** [comment]
Were you able to recreate the issue in #567? You only added a test here and didn't change any source code so either the bug doesn't exist or this doesn't fix it.

**Comment by kevgo** [comment]
I wasn't able to recreate the failure, but this spec verifies the described scenario. Either the bug got fixed in the meantime through unrelated changes, or its still there and this spec will help pinpointing it later. In any case, this PR makes sense in the current situation IMO.

**Comment by charlierudolph** [comment]
I think this test already verifies this as you are killing a branch that has a child and a parent branch
https://github.com/Originate/git-town/blob/master/features/git-kill/current_branch/on_feature_branch/with_child_branches.feature

**Comment by kevgo** [comment]
Ah, great catch! I have removed my new spec, and renamed the existing one to better reflect that it tests the situation with both parent and child branch.

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
