### PR TITLE
Fix spec structure issue

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun @ricmatsui 

Some of the git-rename-branch specs had setup code in the `result` scenario.

### CODE REVIEW

**Comment by charlierudolph** [comment]
nice. :ship:

**Comment by charlierudolph** [comment]
Actually looking at these do we need the background step? They could be combined to just be a single scenario.

**Comment by kevgo** [comment]
I think a while ago we said we like the separation into "background" and "result". Looking at this again, I'm actually okay just merging such specs into a single coherent scenario. I don't think the separation adds much readability. What do you think?

**Comment by charlierudolph** [comment]
I'm fine removing the separation. @allewun @ricmatsui any thoughts?

**Comment by kevgo** [comment]
Okay, I'll remove the `Background` section in feature specs that have only one scenario separately from all feature specs.

**Pull request closed without merging**
