### PR TITLE
Improve branch names

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @allewun 

Inspired by some other changes we did, this PR improves the names of braches in specs

### CODE REVIEW

**Comment by kevgo** [comment]
tests fixed, please take a look now

**Comment by charlierudolph** [comment]
This is the third iteration of branch names:

original: feature and dead-feature
old rename by you: active-feature and orphaned-feature
current rename by you: current-feature and other-feature

I'd suggest we create an issue that comes up with a naming standard we agree to update the features to and use going forward  (we can even add documentation for other developers). I'd prefer to stop these sporadic changes that occur on just a feature tests a time (and that I don't think make much of a difference)

**Comment by kevgo** [comment]
Fair point. Yes, I'm evolving the branch names. 

* Originally I thought having very specific examples is helpful for understanding a scenario. 

* Over the course of adding more feature specs, I realized that this leads to a large variety of branch names with narrow meaning, which creates an unnecessary amount of entropy. So I made them a bit more generic, while still representing particular usage scenarios. This was striking a better balance between understandability and overall maintainability.

* Now, going back to the `git kill` specs after a while, I'm coming more and more to the conclusion that a particular usage scenario isn't that important at all, since (a) there are always several usage scenarios for a Git Town command, and (b) a specific scenario isn't really necessary to describe how a command works, and (c) creating specific usage scenarios adds complexity and mental overhead.

I like your idea of coming up with a consistent global branch naming strategy. To prepare that, I'll dig into each feature a bit more, like I did here, and collect some more thoughts. Does that work for you?

**Comment by charlierudolph** [comment]
Yeah, can you please close this and create an issue with the naming scheme you would suggest. We can iterate on it there and once we come to an agreement, we can start renaming branches.

**Comment by kevgo** [comment]
Sorry, I meant my strategy is to drill into several commands and improve branch names towards a common goal as separate PRs. Then see what patterns and best practices emerge, summarize them in a global issue, and then unify the remaining branch names. 

I don't have a full overview of what the optimal branch naming strategy is at this point. If its okay with you, I'd like to get this PR in. Even if its not the final solution, it gets us one step closer to it.

**Comment by charlierudolph** [comment]
I don't think any more branch renames should go in until we come to a unified naming scheme. Your strategy for determining the branch names is what I was thinking, but simply don't make individual PRs in the process.

**Comment by charlierudolph** [comment]
:ship:

**Pull request closed without merging**
